INSERT INTO `relationship_types` (`key`, `label`, `inverse_key`, `category`, `sort_order`) VALUES
('spouse', 'Spouse', 'spouse', 'family', 10),
('partner', 'Partner', 'partner', 'family', 20),
('parent', 'Parent', 'child', 'family', 30),
('child', 'Child', 'parent', 'family', 40),
('sibling', 'Sibling', 'sibling', 'family', 50),
('grandparent', 'Grandparent', 'grandchild', 'family', 60),
('grandchild', 'Grandchild', 'grandparent', 'family', 70),
('relative', 'Relative', 'relative', 'family', 80),
('friend', 'Friend', 'friend', 'social', 100),
('neighbour', 'Neighbour', 'neighbour', 'social', 110),
('acquaintance', 'Acquaintance', 'acquaintance', 'social', 120),
('colleague', 'Colleague', 'colleague', 'work', 200),
('manager', 'Manager', 'report', 'work', 210),
('report', 'Report', 'manager', 'work', 220),
('employer', 'Employer', 'employee', 'work', 230),
('employee', 'Employee', 'employer', 'work', 240),
('member', 'Member of', 'has_member', 'work', 250),
('has_member', 'Has member', 'member', 'work', 260),
('owner', 'Owner', 'pet', 'pet', 300),
('pet', 'Pet', 'owner', 'pet', 310),
('vet', 'Vet', 'patient', 'care', 400),
('patient', 'Patient', 'vet', 'care', 410),
('doctor', 'Doctor', 'client', 'care', 420),
('client', 'Client', 'doctor', 'care', 430),
('other', 'Other', 'other', 'other', 900);
